source $HOME/.vim/plugins.vim
source $HOME/.vim/settings.vim
source $HOME/.vim/macvim.vim
source $HOME/.vim/functions.vim
source $HOME/.vim/commands.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/mappings.vim
source $HOME/.vim/plugins.unite.vim
source $HOME/.vim/plugins.neocomplete.vim
source $HOME/.vim/plugins.neosnippet.vim
source $HOME/.vim/plugins.lightline.vim
source $HOME/.vim/plugins.misc.vim
